Introduction to Tensors

In [ ]:
# Importing Tensforflow
import tensorflow as tf
print(tf.__version__)

import numpy as np

2.8.2


CREATING TENSORS WITH tf.constant

In [ ]:
# Create Tensors With tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking the number of dimensions of a Tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Creating A vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Checking The Dimension Of Our Vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[21, 7],
                      [7, 21]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21,  7],
       [ 7, 21]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[21., 7.],
                              [5., 3.],
                              [9., 4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[21.,  7.],
       [ 5.,  3.],
       [ 9.,  4.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a Tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

CREATING TENSORS WITH tf.Variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor = tf.Variable([21, 7])
unchangeable_tensor = tf.constant([21, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([21,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([21,  7], dtype=int32)>)

In [ ]:
# Let's try to change one of the elements in our Changeable Tensor
changeable_tensor[0] =  24
changeable_tensor

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(24)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([24,  7], dtype=int32)>

In [ ]:
# Let's try to change one of the elements in our Unchangeable Tensor
unchangeable_tensor[0] =  24
unchangeable_tensor

In [ ]:
unchangeable_tensor[0].assign(24)
unchangeable_tensor

CREATING RANDOM TENSORS

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))


random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))


# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffle the order of elements in a tensor

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
# Shuffle our non- shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Other ways to make Tensors

In [ ]:
# Creating a tensor of all ones
tf.ones([7, 21])

<tf.Tensor: shape=(7, 21), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Cretaing a tensor of all zeroes
tf.zeros(shape=(7,6))

<tf.Tensor: shape=(7, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

Turn Numpy arrays into Tensors

In [ ]:
# We can also turn Numpy arrays into Tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix)
# Y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(2,6,2))
A

<tf.Tensor: shape=(2, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

### Getting Information From Tensors

* Shape
* Rank
* Axis Or Dimension
* Size

In [ ]:
# Create a rank 4 Tensor
rank4_tensor = tf.zeros(shape = [2,3,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank4_tensor.shape, rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print('Datatype Of every elements :', rank4_tensor.dtype)
print('Number Of dimensions (rank) :', rank4_tensor.ndim)
print('Shape Of tensor :', rank4_tensor.shape)
print('Elements along the 0th axis :', rank4_tensor.shape[0])
print('Elements along the last axis :', rank4_tensor.shape[-1])
print('Total number of elements in our tensor :', tf.size(rank4_tensor).numpy())


Datatype Of every elements : <dtype: 'float32'>
Number Of dimensions (rank) : 4
Shape Of tensor : (2, 3, 4, 5)
Elements along the 0th axis : 2
Elements along the last axis : 5
Total number of elements in our tensor : 120


### Indexing Tensors

In [ ]:
# Get the first 2 elements of each dimension
rank4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor ( 2 dimensions)
rank2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank2_tensor.shape, rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each of row of our rank 2 tensor
rank2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Adding the extra dimension to our rank 2 tansor
rank3_tensor = rank2_tensor[..., tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1, 1, 1), dtype=int32, numpy=
array([[[[[10]]],


        [[[ 7]]]],



       [[[[ 3]]],


        [[[ 4]]]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank2_tensor, axis=-1) # '-1' means expanding the final axis

<tf.Tensor: shape=(2, 2, 1, 1, 1), dtype=int32, numpy=
array([[[[[10]]],


        [[[ 7]]]],



       [[[[ 3]]],


        [[[ 4]]]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2_tensor, axis=0) # expanding the 0th-axis

<tf.Tensor: shape=(1, 2, 2, 1, 1), dtype=int32, numpy=
array([[[[[10]],

         [[ 7]]],


        [[[ 3]],

         [[ 4]]]]], dtype=int32)>

### Manipulating Tensors (Tensor Operations)
**Basic Operations**

In [ ]:
tensor = tf.constant([[21, 7], [5, 24]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 17],
       [15, 34]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210,  70],
       [ 50, 240]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, -3],
       [-5, 14]], dtype=int32)>

In [ ]:
# We can use the built in tensorflow function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210,  70],
       [ 50, 240]], dtype=int32)>

**Matrix Multiplication**

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21,  7],
       [ 5, 24]], dtype=int32)>

In [ ]:
tensor * tensor # element-wise operation

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[441,  49],
       [ 25, 576]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[476, 315],
       [225, 611]], dtype=int32)>

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[476, 315],
       [225, 611]], dtype=int32)>

In [ ]:
# Creating a (3, 2) tensor
X = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])

# Creating another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
X @ Y

In [ ]:
tf.matmul(X, Y)

In [ ]:
# Let's change the shape of Y
Y = tf.reshape(Y, shape=(2, 3))
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

##DOT PRODUCT

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perforrming matrix multiplication b/w X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Performing matrix multiplication b/w X and Y (reshaped)

tf.matmul(X,tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Checking the values of Y, reshape Y and transposed Y
print('Normal Y :')
print(Y, '\n')

print('Y reshaped to (2, 3) :')
print(tf.reshape(Y, (2, 3)), '\n')

print('Y transposed :')
print(tf.transpose(Y))

Normal Y :
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3) :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

###CHANGING THE DATA TYPES

In [ ]:
# Create  a new tensor with default datatype (float 32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 21])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 21.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 21.], dtype=float16)>

### AGGREGATING

In [ ]:
F = tf.constant([-7, -10])
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Creating A Random with values b/w 0 and 100 of size 50
G = tf.constant(np.random.randint(0, 100, size=50))
G

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([92, 39, 49, 95, 86, 57, 28, 46, 16, 44, 30, 13, 78, 41, 42, 42, 85,
       49, 15, 33, 36, 22, 71, 79, 40, 75, 46, 95, 31, 92, 98, 78, 68,  6,
       52, 12, 86, 17, 75, 90, 86, 34, 36,  9, 43, 74, 47, 56,  5, 29])>

In [ ]:
tf.size(G), G.shape, G.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Finding the minimum
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [ ]:
# Finding the maximum
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Finding the mean
tf.reduce_mean(G)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
# Finding The sum
tf.reduce_sum(G)

<tf.Tensor: shape=(), dtype=int64, numpy=2568>

In [ ]:
# Finding the variance
tf.math.reduce_variance(tf.cast(G, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=749.6304>

In [ ]:
# Finding the Standard Deviation
tf.math.reduce_std(tf.cast(G, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.37938>

###FINDING THE POSITIONAL MAXIMUM AND MINIMUM

In [ ]:
# Creating a new tensor for finding the positional maximum and minimum
tf.random.set_seed(42)
H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the Positional Maximum
tf.argmax(H)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
H[tf.argmax(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of H
tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
H[tf.argmax(H)] == tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Finding the positional minimum
tf.argmin(H)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Indexing the positional minimum
H[tf.argmin(H)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### SQUEEZING A TENSOR (Removing All Single Dimensions)

In [ ]:
# Creating a tensor
tf.random.set_seed(42)
I = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
I

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
I.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
I_squeezed = tf.squeeze(I)
I_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### ONE HOT ENCODING

In [ ]:
# Creating a list of indices
some_list = [0, 1, 2, 3]

# One hot encoding our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specifying custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value='Yo I Love Deep Learning', off_value='I also like to Code')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo I Love Deep Learning', b'I also like to Code',
        b'I also like to Code', b'I also like to Code'],
       [b'I also like to Code', b'Yo I Love Deep Learning',
        b'I also like to Code', b'I also like to Code'],
       [b'I also like to Code', b'I also like to Code',
        b'Yo I Love Deep Learning', b'I also like to Code'],
       [b'I also like to Code', b'I also like to Code',
        b'I also like to Code', b'Yo I Love Deep Learning']], dtype=object)>

### SQUARING, LOG AND SQUARE ROOT

In [ ]:
# Create a new tensor
J = tf.range(1, 10)
J

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square J
tf.square(J)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Finding The Square Root ( error)
tf.sqrt(J)

In [ ]:
# Finding The Square Root
tf.sqrt(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Finding The log
tf.math.log(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### TENSORS AND NUMPY

In [ ]:
# Creating a tensor directly from numpy array
K = tf.constant(np.array([3., 7., 10.]))
K

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Converting tensor K to a Numpy Array
K.numpy(), type(K.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]